version: '3.3'
services:
  taskservice:
    image: taskimage
    container_name: taskcontainer
    build: taskService/
    restart: always
    network_mode: host
    ports:
      - 8084:8084
    depends_on:
      - mongoservice

  mongoservice:
    image: mongo:3.2-jessie
    container_name: mongocontainer1
    ports:
      - 27017:27017
    network_mode: host

  userauthenticationservice:
    container_name: userauthenticationcontainer
    image: authenticationimage
    network_mode: host
    build: authenticationservice/
    ports:
      - 8083:8083
    depends_on:
      - mysqlservice

  mysqlservice:
    image: mysql:5.5
    ports:
      - 3306:3306
    container_name: mysql-container
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: zxcvbnmA@3456
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"


  apigatewayservice:
    image: apigatewayimage
    container_name: apigatewaycontainer
    network_mode: host
    build: apigateway/
    ports:
      - 9000:9000

  eurekaserver:
    image: eureka-image
    build: eurekaservice/
    restart: always
    network_mode: host
    ports:
      - 8761:8761

  archiveservice:
    image: archiveimage
    container_name: archivecontainer
    build: archiveService/
    restart: always
    network_mode: host
    ports:
      - 8085:8085
    depends_on:
      - mongoservice