server:
  port: 9000
spring:
  application:
    name: to-do-tracker-apigateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
eureka:
 client:
   defaultZone: http://localhost:8761/eureka
   fetchRegistry: true
   registerWithEureka: true